const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEdnb3pjeVZFM1ZjZllxQjZocUtiaFZYUHQ3M29waVYyVTdpYVZyQ0RrST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT1MvYkhWWXp4Zm1kYjViMVl0cmY2WG1VK25BZjJrbmc2Znlwc0pKL2FpST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJNTUlHdkZwSEJ1SmV3RkhGYzBhRm5temg4Mmg1YXdOanlMN20yU1ZKbFZjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVRWRNS0U5UG1JZTg4RitFSEtPMUhBaDBmT3ljdVIxN0FKYjh1UzlDYVRvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1JY2ExR2kxM1JwSWxtRUNibzRIZXpUZWtQV0xJdU96OC9pcEt6TDlwR2s9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik14bDhTQWtxWXNzMWpENXpuVzZDN2xyWHUwSzBKZlp6Qjhob3RzdnU3Vnc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0tsRW4wT05yL2lGblRvU2V1aFFzeU5TWlBiZjA3ckhoVjhmNkRiSE9Gcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidFhhT0xUclBidHZobm94TEZyMGxBNm5SMjVBa1RTSFpZTVJZSFUyRDJqUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNuN3dvQVNDMmF1aFVleGIwWFlub2QrdFNqRFhhT0dPT0lyWWROUmlSNXNId29aYnFkWjJEa3ZnZVJJSnhEMWNQakI2SmxDTHdZeDBkcVdwdU05MUFRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NDYsImFkdlNlY3JldEtleSI6IjNQbUtqd01oejQ0V3huYThqQWp1U3Baa010RU1NY0dUcmZpTnZOcXVjWWc9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3ODU3NjA1MzFAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRjYwMDg1NUI3N0ZFN0YwMjU4OUZEMUE4NEY5QkY1Q0MifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0MDQwNDg2OH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiVTBSQldFQ0tSOWE4clRIQkRld091ZyIsInBob25lSWQiOiJkYTgyN2FlNS1lYzcyLTRiNzktOTE5My02YWY4OTVlMzg1OTkiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOGFYWldxSGVWNUZiTVRualZYbE5tNXZwMU9BPSJ9LCJyZWdpc3RlcmVkIjpmYWxzZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ0K3AwekZvSUdYSGNUWElEbitHb290V05sNm89In0sInJlZ2lzdHJhdGlvbiI6e30sImFjY291bnQiOnsiZGV0YWlscyI6IkNNdVp1c0VCRVBMdzhiMEdHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJNN0hVcVMrdGlmYktnbVNxaEdPSGlhb3pCZEd0dlZ1aHVlUlYwMHo0ckVnPSIsImFjY291bnRTaWduYXR1cmUiOiJUQlZuMmZRVTZWYXZyNmhXL1gwd2lSVjlWTWtvd09uVlNQWnRkcFJvVC9IbkwzQmdkZjZjUG5WK0h5b1lSbjQ2ZUhGMHVFY01xQ0JxRjVkUFJ5Q3JEZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiQzlzR3FDaG5sNUU4SEhsOUZYNEFGeGlTN05VUkNlQUhodWd4S05UdVpRVDljUVNpTm9rMW5vSktkbjk4dEhWdHJDWHF6ZTBNWnNUWTh6SXMxSlJWREE9PSJ9LCJtZSI6eyJpZCI6Ijk0Nzg1NzYwNTMxOjRAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiQ2hhdHp5In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6Ijk0Nzg1NzYwNTMxOjRAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVE94MUtrdnJZbjJ5b0prcW9Samg0bXFNd1hScmIxYm9ibmtWZE5NK0t4SSJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc0MDQwNDg2NSwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFCWGgifQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "94785760531",
  "OWNER_NAME": process.env.OWNER_NAME || "Samith",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "92",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
