name: Python application

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can change this version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests (if any)
      run: |
        # Add your test command here, e.g., for pytest:
        pytest

    - name: Upload Test Results (optional)
      if: failure()  # Only upload on failure
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-reports/
